services:
  postgres:
    image: postgres:16
    container_name: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      barknet:
        aliases:
          - postgres

  metabase:
    image: metabase/metabase
    container_name: metabase
    depends_on:
      - postgres
    ports:
      - "${METABASE_PORT:-3000}:3000"
    environment:
      MB_DB_TYPE: ${MB_DB_TYPE}
      MB_DB_DBNAME: ${MB_DB_DBNAME}
      MB_DB_PORT: ${MB_DB_PORT}
      MB_DB_USER: ${MB_DB_USER}
      MB_DB_PASS: ${MB_DB_PASS}
      MB_DB_HOST: ${MB_DB_HOST}
    networks:
      barknet:
        aliases:
         - metabase

  sheets-exporter:
    build: ./apps-script/google-sheets-export
    image: infra-sheets-exporter:1.0
    env_file:
      - ./.env
    working_dir: /app
    # which files to mount into the docker container
    volumes:
      - ./apps-script/google-sheets-export/src:/app/src
      - ./apps-script/google-sheets-export/.secrets/service-account.json:/app/.secrets/service-account.json:ro
    command: python ./src/sheets-exporter.py
    networks:
      - barknet

volumes:
  pg_data:

networks:
  barknet:
    name: barknet
